In [1]:
x <- matrix(1:10, nrow = 2, ncol = 5)

In [2]:
x

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [3]:
x <- factor(c("yes", "no", "no", "yes", "maybe"), levels = c("no", "maybe", "yes"))

In [4]:
x

[1] yes   no    no    yes   maybe
Levels: no maybe yes

In [6]:
table(x)

x
   no maybe   yes 
    2     1     2 

In [7]:
unclass(x)

[1] 3 1 1 3 2
attr(,"levels")
[1] "no"    "maybe" "yes"

In [8]:
x <- "Hello World!"

In [9]:
x

[1] "Hello World!"

In [21]:
data <- read.csv("foo.txt", comment.char = "#")
data

id nome                 idade
1 1  Abelardo Vieira Mota 28   
2 2  Juliana Vieira Mota  29   
3 3  Carl Jung            65   
4 4  Clarice Foospector   54

In [22]:
dput(data)

structure(list(id = 1:4, nome = structure(c(1L, 4L, 2L, 3L), .Label = c("Abelardo Vieira Mota", 
"Carl Jung", "Clarice Foospector", "Juliana Vieira Mota"), class = "factor"), 
    idade = c(28L, 29L, 65L, 54L)), .Names = c("id", "nome", 
"idade"), class = "data.frame", row.names = c(NA, -4L))


In [23]:
dput(data, file = "foo.R")

In [24]:
new.y = dget("foo.R")

In [25]:
new.y

id nome                 idade
1 1  Abelardo Vieira Mota 28   
2 2  Juliana Vieira Mota  29   
3 3  Carl Jung            65   
4 4  Clarice Foospector   54

In [29]:
x <- "foo"
y <- data.frame(a = 1, b = "2")

dump(c("x", "y"), file = "data.R")

rm(x, y)

In [30]:
source("data.R")

In [31]:
x

[1] "foo"

In [32]:
y

a b
1 1 2

In [33]:
x <- c("a", "b", "c", "c", "d", "a")

In [34]:
x[1]

[1] "a"

In [35]:
x[2]

[1] "b"

In [37]:
x[x > "b"]

[1] "c" "c" "d"

In [39]:
u <- x > "b"

u

[1] FALSE FALSE  TRUE  TRUE  TRUE FALSE

In [40]:
x[u]

[1] "c" "c" "d"

In [43]:
x <- list(foo = 1:4, bar = 0.6)
x

$foo
[1] 1 2 3 4

$bar
[1] 0.6

In [44]:
x[1] # list

$foo
[1] 1 2 3 4

In [45]:
x[[1]] # just the sequence

[1] 1 2 3 4

In [46]:
x$bar # just the element

[1] 0.6

In [49]:
x$foo

[1] 1 2 3 4

In [47]:
x[["bar"]]

[1] 0.6

In [48]:
x["bar"]

$bar
[1] 0.6

In [52]:
x[[c(1,3)]]

[1] 3

In [53]:
x[[1]][[3]]

[1] 3

In [54]:
x <- matrix(1:6, 2, 3)

x[, 2]

[1] 3 4

In [57]:
x[1, 2] # vector of length 1

[1] 3

In [58]:
x[1, 2, drop = F] # 1x1 matrix

[,1]
[1,] 3

In [59]:
x[, 2, drop = F] # matrix

[,1]
[1,] 3   
[2,] 4

In [63]:
x <- list(aardvark = 1:5)

x[["a", exact = F]] # matches aardvark

[1] 1 2 3 4 5

In [64]:
x$a # matches aardvark

[1] 1 2 3 4 5

In [65]:
x <- c(1, 2, NA, 4, NA, 6)

x

[1]  1  2 NA  4 NA  6

In [66]:
bad <- is.na(x)

x[!bad]

[1] 1 2 4 6

In [67]:
x[!is.na(x)]

[1] 1 2 4 6

In [72]:
x <- c(1, 2, NA, 4, 7, NA)
y <- c(NA, "b", NA, "d", NA, "f")

good <- complete.cases(x, y)

good

x[good]
y[good]

[1] FALSE  TRUE FALSE  TRUE FALSE FALSE

[1] 2 4

[1] "b" "d"

In [73]:
x <- 1:4
y <- 6:9

x+y

[1]  7  9 11 13

In [74]:
x > 2

[1] FALSE FALSE  TRUE  TRUE

In [75]:
x * y

[1]  6 14 24 36

In [80]:
x <- matrix(1:4, 2, 2)
y <- matrix(rep(10, 4), 2, 2)

x
y
x * y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 10   10  
[2,] 10   10

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [81]:
x / y

[,1] [,2]
[1,] 0.1  0.3 
[2,] 0.2  0.4

In [82]:
x %*% y

[,1] [,2]
[1,] 40   40  
[2,] 60   60

In [83]:
class(4L)

[1] "integer"

In [84]:
class(c(4, "a", T))

[1] "character"

In [85]:
cbind(c(1, 3, 5), c(3, 2, 10))

[,1] [,2]
[1,] 1     3  
[2,] 3     2  
[3,] 5    10

In [88]:
list(2, "a", "b", T)[[2]]

[1] "a"

In [90]:
class(1:4 + 2)

[1] "numeric"

In [93]:
x <- 1:20

x[x > 10] <- 3

x

[1]  1  2  3  4  5  6  7  8  9 10  3  3  3  3  3  3  3  3  3  3

In [98]:
data = read.csv("../week 1/hw1_data.csv")

head(data)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [102]:
data[1:2, ]

Ozone Solar.R Wind Temp Month Day
1 41    190     7.4  67   5     1  
2 36    118     8.0  72   5     2

In [105]:
nrow(data)

[1] 153

In [107]:
data[152:153, ]

Ozone Solar.R Wind Temp Month Day
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

In [111]:
data[47, 'Ozone']

[1] 21

In [113]:
sum(is.na(data$Ozone))

[1] 37

In [114]:
mean(data$Ozone[!is.na(data$Ozone)])

[1] 42.12931

In [134]:
not_na_Ozone_Solar <- complete.cases(data$Ozone, data$Solar.R)

sub1 <- data[not_na_Ozone_Solar, ]

con1 <- sub1$Ozone > 31
con2 <- sub1$Temp > 90

sub2 <- sub1[con1 & con2, ]

mean(sub2$Solar.R)

[1] 212.8

In [139]:
mon_eq_6 = data[data$Month == 6, ]

mean(mon_eq_6$Temp)

[1] 79.1

In [141]:
mean(mon_eq_6$Temp[!is.na(mon_eq_6$Temp)])

[1] 79.1

In [142]:
mean(data$Temp)

[1] 77.88235

In [151]:
max(data[!is.na(data$Ozone) & data$Month == 5, "Ozone"])

[1] 115